### ISSUE TITLE
install error for kylin which is based on el8 on aarch64

### ISSUE THREAD

**Issue by ElapsedSoul** [mastertheknife/clickhouse-rpms#1]
```shell
[root@kylin2 data]# dnf install clickhouse-client clickhouse-server
Last metadata expiration check: 0:00:16 ago on 2021年03月31日 星期三 09时30分38秒.
Error: 
 Problem 1: package clickhouse-server-21.3.3.14-3.el8.aarch64 requires clickhouse-common-static = 21.3.3.14-3.el8, but none of the providers can be installed
  - cannot install the best candidate for the job
  - nothing provides msgpack needed by clickhouse-common-static-21.3.3.14-3.el8.aarch64
  - nothing provides capnproto-libs needed by clickhouse-common-static-21.3.3.14-3.el8.aarch64
  - nothing provides libcapnp.so.0.7.0()(64bit) needed by clickhouse-common-static-21.3.3.14-3.el8.aarch64
  - nothing provides libcapnpc.so.0.7.0()(64bit) needed by clickhouse-common-static-21.3.3.14-3.el8.aarch64
  - nothing provides libgsasl needed by clickhouse-common-static-21.3.3.14-3.el8.aarch64
  - nothing provides libicudata.so.60()(64bit) needed by clickhouse-common-static-21.3.3.14-3.el8.aarch64
  - nothing provides libicui18n.so.60()(64bit) needed by clickhouse-common-static-21.3.3.14-3.el8.aarch64
  - nothing provides libicuuc.so.60()(64bit) needed by clickhouse-common-static-21.3.3.14-3.el8.aarch64
  - nothing provides libkj.so.0.7.0()(64bit) needed by clickhouse-common-static-21.3.3.14-3.el8.aarch64
 Problem 2: package clickhouse-client-21.3.3.14-3.el8.aarch64 requires clickhouse-common-static = 21.3.3.14-3.el8, but none of the providers can be installed
  - cannot install the best candidate for the job
  - nothing provides msgpack needed by clickhouse-common-static-21.3.3.14-3.el8.aarch64
  - nothing provides capnproto-libs needed by clickhouse-common-static-21.3.3.14-3.el8.aarch64
  - nothing provides libcapnp.so.0.7.0()(64bit) needed by clickhouse-common-static-21.3.3.14-3.el8.aarch64
  - nothing provides libcapnpc.so.0.7.0()(64bit) needed by clickhouse-common-static-21.3.3.14-3.el8.aarch64
  - nothing provides libgsasl needed by clickhouse-common-static-21.3.3.14-3.el8.aarch64
  - nothing provides libicudata.so.60()(64bit) needed by clickhouse-common-static-21.3.3.14-3.el8.aarch64
  - nothing provides libicui18n.so.60()(64bit) needed by clickhouse-common-static-21.3.3.14-3.el8.aarch64
  - nothing provides libicuuc.so.60()(64bit) needed by clickhouse-common-static-21.3.3.14-3.el8.aarch64
  - nothing provides libkj.so.0.7.0()(64bit) needed by clickhouse-common-static-21.3.3.14-3.el8.aarch64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by ElapsedSoul** [comment]
I had build a binary without openssl for this OS. I'm surprised of your rpm package. Haha, How do you do,my friend!

**Comment by mastertheknife** [comment]
Hey and thank you :-)

About: libcapnp*\libkj*, msgpack and libgsasl, these exist in EPEL.
In RHEL\CentOS 8 often "dnf install epel-release" will do.
But if epel-release is not found, this will do it:
```dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm```

About libicu*, these are from libicu from baseos:
```
removed:~ $ dnf whatprovides '*/libicuuc.so.60'
Last metadata expiration check: 0:35:30 ago on Wed 31 Mar 2021 03:06:18 PM IDT.
libicu-60.3-2.el8_1.i686 : International Components for Unicode - libraries
Repo        : baseos
Matched from:
Filename    : /usr/lib/libicuuc.so.60

libicu-60.3-2.el8_1.x86_64 : International Components for Unicode - libraries
Repo        : @System
Matched from:
Filename    : /usr/lib64/libicuuc.so.60

libicu-60.3-2.el8_1.x86_64 : International Components for Unicode - libraries
Repo        : baseos
Matched from:
Filename    : /usr/lib64/libicuuc.so.60
```

This is strange, libicu should exist in the main OS repository.
I have to admit i have no experience with Kylin, this is interesting issue. I will try taking a look in Kylin's repository and reply back soon.

**Comment by mastertheknife** [comment]
I did some searching online about KylinOS.
It seems that KylinOS is not a 100% binary compatible clone of RHEL. They even use different %dist tag in their RPMs, "ky10" instead of "el8".
I managed to find their repository online. The x86_64 one has libicu, but different version than RHEL (62 vs 60). ~The aarch64 one is missing libicu completely.
A possible workaround is to install libicu from CentOS8 aarch64, and it might just work. It doesn't depend on other libraries except standard core ones (libc, stdc++ etc):
```dnf install http://mirror.centos.org/centos/8/BaseOS/aarch64/os/Packages/libicu-60.3-2.el8_1.aarch64.rpm```~

EDIT: My mistake, the aarch64 repository also has libicu, but also version 62.
So looks KylinOS has a newer version of libicu than RHEL\CentOS\Oracle Linux. A downgrade of this package can break other applications that depend on it.
If you need this to work, you can rebuild the RPMs for KylinOS by installing the SRPM and running `rpmbuild -ba /root/rpmbuild/SPECS/clickhouse.spec`. You'll receive an error from rpmbuild about *-devel packages missing, Need to install those.

**Comment by ElapsedSoul** [comment]
> Hey and thank you :-)
> 
> About: libcapnp*\libkj*, msgpack and libgsasl, these exist in EPEL.
> In RHEL\CentOS 8 often "dnf install epel-release" will do.
> But if epel-release is not found, this will do it:
> `dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm`
> 
> About libicu*, these are from libicu from baseos:
> 
> ```
> removed:~ $ dnf whatprovides '*/libicuuc.so.60'
> Last metadata expiration check: 0:35:30 ago on Wed 31 Mar 2021 03:06:18 PM IDT.
> libicu-60.3-2.el8_1.i686 : International Components for Unicode - libraries
> Repo        : baseos
> Matched from:
> Filename    : /usr/lib/libicuuc.so.60
> 
> libicu-60.3-2.el8_1.x86_64 : International Components for Unicode - libraries
> Repo        : @System
> Matched from:
> Filename    : /usr/lib64/libicuuc.so.60
> 
> libicu-60.3-2.el8_1.x86_64 : International Components for Unicode - libraries
> Repo        : baseos
> Matched from:
> Filename    : /usr/lib64/libicuuc.so.60
> ```
> 
> This is strange, libicu should exist in the main OS repository.
> I have to admit i have no experience with Kylin, this is interesting issue. I will try taking a look in Kylin's repository and reply back soon.

```shell
[root@kylin2 ~]# dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm


Last metadata expiration check: 1:30:39 ago on 2021年04月01日 星期四 07时20分02秒.
epel-release-latest-8.noarch.rpm                                                                                                                              16 kB/s |  22 kB     00:01    
Error: 
 Problem: conflicting requests
  - nothing provides redhat-release >= 8 needed by epel-release-8-10.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
It seems I have to remove the required of redhat-release for epel-release-8-10.el8.noarch in its spec to test to install,which likes I had done to redhat-lsb for rpm of el8 installed on kylinOS.

**Comment by ElapsedSoul** [comment]
> I had build a binary without openssl for this OS. I'm surprised of your rpm package. Haha, How do you do,my friend!

@mastertheknife I had build a binary for kylinOS with unenable the ldap and ssl support under the guide [clickhouse issue](<https://github.com/ClickHouse/ClickHouse/issues/19028>) replies.
The binary works well with unenable the ldap and ssl support on kylinOS. 
Now I doubt if the clickhouse really need these libraries above?

**Comment by mastertheknife** [comment]
Hi,
Yeah, it should be possible to compile without LDAP and probably without SSL either, or to compile with the bundled LDAP and SSL.
If you rebuild the RPMs from the SRPM it'll probably work too, because it'll tie the new RPMs to the versions used in KylinOS.
Its really not a 100% binary-compatible RHEL8 clone. There is no way other than rebuild or to use the official RPMs, which have everything bundled in, very flexible at the cost of size.
